### ISSUE TITLE
Assign assemblers and algos for description

### ISSUE THREAD

**Issue by ar0ch** [biol7210-genomes/assemblers#2]
Select an assembly program from the main assembly README.

**Comment by ar0ch** [comment]
Velvet @tannishtha

**Comment by ar0ch** [comment]
PEAR: Namratha

**Comment by ar0ch** [comment]
@agombolay Aligngraph

**Comment by ar0ch** [comment]
@afrancis40 PaBr

@nkalsi PEAR

**Comment by lee-t** [comment]
I'll do Pilon, and maybe also DISCOVAR
